"""Describes each customizable gene byte in an El-Fish .ROE file: which byte it lives at, what it
changes, and the value range each slider is allowed to use.

This data mirrors the names, descriptions, and section order of the companion web guide
(El-Fish Fish Customisation Guide) exactly -- when that guide is edited, re-run the sync so
this file stays in lockstep: same bytes, same order, same section/group structure, same
labels and descriptions. A byte the guide drops should be dropped from here too.

A handful of bytes do double duty and appear TWICE in the guide, under two different
headings -- most often a Shape slider that also fully disables the fin at value 0. The guide
is the source of truth, so each shows up here as two separate entries too (two separate rows
in the UI), one per offset value -- NOT merged into one. Moving either one's slider updates
the other automatically at runtime, since they're the same underlying byte; each entry's
`changes` text ends with an auto-generated note pointing at where its sibling entry lives.
Only genuinely identical duplicate rows (the guide repeating the exact same row twice, a
copy/paste slip) are collapsed down to one.

safe_min/safe_max are each slider's actual min/max -- most genes stop well short of the guide's
declared range because the picture stops changing (or the game destabilizes) before the byte's
theoretical max, so the slider simply doesn't go there; these come from pixel-diffing the
bundled preview images, not from the guide's text. `safe_note` IS the guide's own declared
"Value Range" text verbatim, shown to the user as-is even where it's wider than the slider.

`section` is "Fins", "Body", or "Other" -- the top-level tab a gene lives under, matching the
guide's <h2> headings. `subsection` is the guide's <h3> heading within a section (e.g. "Shape",
"Colour", "Pattern", "Enable/Disable" under Fins) or None where the guide has no such heading
(Body and Other). `group` is the guide's collapsible sub-heading (e.g. "Dorsal fin", "Body
Shape", "Eyes") -- the finest grouping level, always present.
"""

GENES_ALL = [
    # ======================================== Fins ========================================
    # -- Enable/Disable ----------------------------------------------
    dict(offset=0x2A7, label='Dorsal 1', section='Fins', subsection='Enable/Disable', group='Enable/Disable', changes='Enables/disables dorsal fin 1', low=None, high=None, safe_min=0, safe_max=96, safe_note='0 = No fin', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A9, label='Dorsal 2', section='Fins', subsection='Enable/Disable', group='Enable/Disable', changes='Enables/disables dorsal fin 2', low=None, high=None, safe_min=0, safe_max=128, safe_note='0 = No fin', real_range='Not established', crash_risk=False, discrete_values=[0, 19, 61, 100, 128]),
    dict(offset=0x2AF, label='Pectoral', section='Fins', subsection='Enable/Disable', group='Enable/Disable', changes='Enables/disables pectoral fin', low=None, high=None, safe_min=0, safe_max=87, safe_note='0 = No fin', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2B3, label='Pelvic', section='Fins', subsection='Enable/Disable', group='Enable/Disable', changes='Enables/disables pelvic fin', low=None, high=None, safe_min=0, safe_max=97, safe_note='0 = No fin', real_range='Not established', crash_risk=False, discrete_values=[0, 3, 71, 97]),
    dict(offset=0x2AD, label='Anal', section='Fins', subsection='Enable/Disable', group='Enable/Disable', changes='Enables/disables anal fin', low=None, high=None, safe_min=0, safe_max=100, safe_note='0 = No fin', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x319, label='Tail', section='Fins', subsection='Enable/Disable', group='Enable/Disable', changes='Makes tiny, but no full disable flag found', low=None, high=None, safe_min=0, safe_max=100, safe_note='0 = smallest', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Shape / Dorsal fin ------------------------------------------
    dict(offset=0x2A7, label='Dorsal fin length', section='Fins', subsection='Shape', group='Dorsal fin', changes='Fin grows from the front to the back', low=None, high=None, safe_min=0, safe_max=96, safe_note='0-99', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A6, label='Dorsal fin recede', section='Fins', subsection='Shape', group='Dorsal fin', changes='Fin recedes from the front to the back', low='Full-length fin (0-31)', high='Shortest fin, receded almost to the rear (97-127; 128-255 = back to full length)', safe_min=0, safe_max=82, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=[0, 6, 32, 57, 82]),
    dict(offset=0x298, label='Dorsal fin start position', section='Fins', subsection='Shape', group='Dorsal fin', changes='How far back the dorsal fin starts', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Real fish never vary this byte — synthetic-only effect', crash_risk=False, discrete_values=None),
    dict(offset=0x2BD, label='Dorsal ray curve', section='Fins', subsection='Shape', group='Dorsal fin', changes='Curve of spines in the fin from forward to backward', low='Rays curve toward the front', high='Rays curve toward the back (baseline ~50 is neutral, in between)', safe_min=0, safe_max=97, safe_note='0-127', real_range='Up to 92', crash_risk=False, discrete_values=None),
    dict(offset=0x2BA, label='Dorsal fin spikiness', section='Fins', subsection='Shape', group='Dorsal fin', changes='Spikiness/roundness/smoothness of fin', low='Fine, smooth, dense serration', high='Fewer, taller, more spread-out spikes', safe_min=0, safe_max=100, safe_note='0-127', real_range='8-88', crash_risk=False, discrete_values=None),
    dict(offset=0x2BB, label='Dorsal fin spikiness', section='Fins', subsection='Shape', group='Dorsal fin', changes='Dorsal fin spikiness, swept towards the front.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2BC, label='Dorsal fin spikiness', section='Fins', subsection='Shape', group='Dorsal fin', changes='Dorsal fin spikiness, swept towards the back.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2B9, label='Dorsal spines', section='Fins', subsection='Shape', group='Dorsal fin', changes='Number of spines/spikes in the fin', low=None, high=None, safe_min=0, safe_max=21, safe_note='0-40', real_range='Not established', crash_risk=False, discrete_values=[0, 3, 9, 15, 21]),
    dict(offset=0x2BE, label='Dorsal spine angle', section='Fins', subsection='Shape', group='Dorsal fin', changes='Spines swept forward to swept back', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2BF, label='Dorsal fin height', section='Fins', subsection='Shape', group='Dorsal fin', changes='Overall height of the dorsal fin', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2C5, label='Dorsal fin height (super tall)', section='Fins', subsection='Shape', group='Dorsal fin', changes='Whole-fin height, much taller than 0x2BF', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2C0, label='Dorsal front spike', section='Fins', subsection='Shape', group='Dorsal fin', changes='Grows spike from front of the fin', low='Small/no front spike', high='Tall, dramatic pointed spike', safe_min=0, safe_max=127, safe_note='27-126', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2C1, label='Dorsal front spikes', section='Fins', subsection='Shape', group='Dorsal fin', changes='Grows first couple of spines', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2C2, label='Dorsal middle spike', section='Fins', subsection='Shape', group='Dorsal fin', changes='Grows middle couple of spines', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2C3, label='Dorsal rear spikes', section='Fins', subsection='Shape', group='Dorsal fin', changes='Grows rear couple of spines.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2C4, label='Dorsal rear spike', section='Fins', subsection='Shape', group='Dorsal fin', changes='Grows rear spike', low='Small/no rear spike', high='Tall, pointy spike extending up and back', safe_min=0, safe_max=127, safe_note='30-127', real_range='0-92', crash_risk=False, discrete_values=None),
    # -- Shape / Second Dorsal Fin -----------------------------------
    dict(offset=0x2C9, label='Second Dorsal fin shape', section='Fins', subsection='Shape', group='Second Dorsal Fin', changes='Changes shape or second (rear) dorsal fin', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A8, label='Second dorsal fin position', section='Fins', subsection='Shape', group='Second Dorsal Fin', changes='Slides second dorsal fin towards tail', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 49, 99]),
    dict(offset=0x2CB, label='Second dorsal fin shape', section='Fins', subsection='Shape', group='Second Dorsal Fin', changes='Changes shape or second (rear) dorsal fin', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 49, 99]),
    dict(offset=0x2CC, label='Second dorsal fin spine rotation', section='Fins', subsection='Shape', group='Second Dorsal Fin', changes='Rotates spines in second dorsal fin', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 49, 99]),
    # -- Shape / Pectoral Fin ----------------------------------------
    dict(offset=0x2AF, label='Pectoral horizontal position', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Moves fin position or flips it', low=None, high=None, safe_min=0, safe_max=87, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2B0, label='Pectoral vertical position', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Slides fin vertically', low='Low on the body', high='High on the body (values 0-7 are an odd exception -- they jump straight to the "reset" position instead of starting the trend)', safe_min=8, safe_max=93, safe_note='8-129', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2FB, label='Pectoral splay', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Stretches fin from small to a splayed fan', low='Tiny, compact dot', high='Large, splayed fan with visible rays', safe_min=0, safe_max=100, safe_note='0-129', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x301, label='Pectoral scale', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Overall scale of fin from almost nothing to huge', low='Fin nearly invisible', high='Normal fin (baseline ~60 is normal-sized; fin nearly vanishes at BOTH 0 and 127+)', safe_min=0, safe_max=100, safe_note='0-129', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x302, label='Pectoral scale (inverse)', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Same as 0x301 but gets smaller as value gets bigger', low='Full-size fin (baseline = biggest)', high='Shrunk to a tiny sliver', safe_min=0, safe_max=100, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2FD, label='Pectoral top stretch', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Top edge stretches horizontally, from cutaway to a spike', low='Collapses into a thin crescent', high='Long, sharp point', safe_min=0, safe_max=127, safe_note='0-129', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2FE, label='Pectoral bottom stretch', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Bottom edge stretches horizontally, from cutaway to a spike', low='Collapses into a thin crescent', high='Long, pointed tip', safe_min=0, safe_max=127, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2B7, label='Pectoral rotation', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Rotates fin edge-on (i.e. towards the screen)', low='Normal, full, face-on fin (0-30)', high='Thin sliver, then fragmented/broken-looking blobs (past ~200)', safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F6, label='Pectoral heart shape', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Increases cutout of 2 half-circles out of the rear of the fin, or extends them to heart shape', low='Round, heart-shaped fin', high='Sharp, twin-pointed concave crescent shape (128-255 = back to round)', safe_min=0, safe_max=100, safe_note='0-127', real_range='Almost always 50 (round); occasionally 51 or 92', crash_risk=False, discrete_values=None),
    dict(offset=0x2F9, label='Pectoral front cutout', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Increases cutout of 2 half-circles at front top and bottom of fin, or extends them.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2B1, label='Pectoral placement', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Rotates fin around the attachment point.', low=None, high=None, safe_min=0, safe_max=84, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=[0, 82, 84]),
    dict(offset=0x2FC, label='Pectoral fin curl (upward)', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Length/curl of the fin towards top', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x300, label='Pectoral fin curl (downward)', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Length/curl of the fin towards bottom', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2FA, label='Pectoral fin angle/rotation', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Rotates the whole fin, changing the thickness', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2FF, label='Pectoral bottom shape', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Changes bottom of fin shape', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F7, label='Pectoral fin curve', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Turns fin into curved shape with cutout', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F8, label='Pectoral fin curve', section='Fins', subsection='Shape', group='Pectoral Fin', changes='Curves fin up and down', low='Tall, elongated oval patch', high='Large, round patch', safe_min=0, safe_max=100, safe_note='0-127 (128-255 alt state)', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Shape / Pelvic Fin ------------------------------------------
    dict(offset=0x2B3, label='Pelvic fin size', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Scales from nothing up to huge', low=None, high=None, safe_min=0, safe_max=97, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=[0, 3, 71, 97]),
    dict(offset=0x311, label='Pelvic fin size (inverted)', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Scales from normal to nothing', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='real fish use); any nonzero shrinks it toward gone', crash_risk=False, discrete_values=None),
    dict(offset=0x26D, label='Pelvic fin flatness', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Hugs the body or pushes it outwards.', low='"Extended" position', high='"Receded" position (values 78-127 only)', safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x306, label='Pelvic fin roundness', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Roundness/extension of front of fin', low=None, high=None, safe_min=0, safe_max=87, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x308, label='Pelvic fin roundness', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Roundness of front of fin (same as 0x306 but inverted)', low=None, high=None, safe_min=0, safe_max=96, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x305, label='Pelvic fin spikiness', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Changes from solid fin to spiky spines', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2B5, label='Pelvic shape type', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Rotates fin around attachment point.', low=None, high=None, safe_min=0, safe_max=106, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=[0, 53, 86, 106]),
    dict(offset=0x307, label='Pelvic fin length', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Extends fin downward', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x310, label='Pelvic fin length', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Extends fin longways (not just downward)', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x30F, label='Pelvic fin length', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Extends the fin toward the rear', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2AE, label='Fin position', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Moves pectoral and pelvic fins at higher values', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 56, 59, 128]),
    dict(offset=0x309, label='Pelvic fin angle', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Rotates pelvic fin from front to back', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x30A, label='Pelvic fin angle', section='Fins', subsection='Shape', group='Pelvic Fin', changes='Same as 0x309 but inverted.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Shape / Anal Fin --------------------------------------------
    dict(offset=0x2AD, label='Anal fin width', section='Fins', subsection='Shape', group='Anal Fin', changes='Extends anal fin toward the tail', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F2, label='Anal fin height', section='Fins', subsection='Shape', group='Anal Fin', changes='Length of the anal fin below the body', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2AC, label='Anal fin slide', section='Fins', subsection='Shape', group='Anal Fin', changes='Slides fin towards the tail', low=None, high=None, safe_min=0, safe_max=98, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2AA, label='Anal fin slide', section='Fins', subsection='Shape', group='Anal Fin', changes='Slides fin towards tail same as 0x2AC but slightly different.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2ED, label='Anal fin rear point', section='Fins', subsection='Shape', group='Anal Fin', changes='Extends spine at rear of the fin', low=None, high=None, safe_min=0, safe_max=127, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2EB, label='Anal fin spine curve', section='Fins', subsection='Shape', group='Anal Fin', changes='Curves anal fin spines toward the front', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2E9, label='Anal fin spine curve', section='Fins', subsection='Shape', group='Anal Fin', changes='Fin spines curves backward', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2EC, label='Anal fin vertical extent', section='Fins', subsection='Shape', group='Anal Fin', changes='Length of anal fin from the bottom of the body.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2EF, label='Anal fin length (super)', section='Fins', subsection='Shape', group='Anal Fin', changes='Anal fin length/height again, but extreme', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F1, label='Anal fin first spine length', section='Fins', subsection='Shape', group='Anal Fin', changes='Extends front spine as a long spike.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F0, label='Anal fin first spines spike', section='Fins', subsection='Shape', group='Anal Fin', changes='Extends the next front couple of spines.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2EA, label='Anal fin spine waviness', section='Fins', subsection='Shape', group='Anal Fin', changes='Spines turn from concave to convex', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2E8, label='Anal fin spine bend', section='Fins', subsection='Shape', group='Anal Fin', changes='Bends the fins spines from forward to backward', low=None, high=None, safe_min=0, safe_max=89, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2F3, label='Anal Fin shape', section='Fins', subsection='Shape', group='Anal Fin', changes='Changes shape of anal fin', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 49, 99]),
    # -- Shape / Tail Fin --------------------------------------------
    dict(offset=0x319, label='Tail length', section='Fins', subsection='Shape', group='Tail Fin', changes='Tiny stub at 0, full size splayed at 127', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x31F, label='Tail scale', section='Fins', subsection='Shape', group='Tail Fin', changes='Scales tail to huge proportions', low=None, high=None, safe_min=32, safe_max=116, safe_note='32-116', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x281, label='Tail vertical height', section='Fins', subsection='Shape', group='Tail Fin', changes='Spreads tail vertically', low='Short/compact tail fin', high='Tall, splayed-out tail fin', safe_min=0, safe_max=100, safe_note='0-90', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x272, label='Tail angle up', section='Fins', subsection='Shape', group='Tail Fin', changes='Rotates the angle of the tail upwards', low='Steep diagonal stripes', high='Steep diagonal stripes (flattens out in the middle of the range instead)', safe_min=0, safe_max=100, safe_note='0-60', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x273, label='Tail angle down', section='Fins', subsection='Shape', group='Tail Fin', changes='Rotates the angle of the tail downwards', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x31A, label='Tail top spine extend', section='Fins', subsection='Shape', group='Tail Fin', changes='Extends spine at top of the tail fin or retracts it towards body', low=None, high=None, safe_min=0, safe_max=126, safe_note='0-126', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x31B, label='Tail top spines extend', section='Fins', subsection='Shape', group='Tail Fin', changes='Extends spines at top of the tail fin or retracts it towards body', low='Curls inward into a concave hook', high='Long, sharp triangular point', safe_min=0, safe_max=127, safe_note='0-124', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x31D, label='Tail bottom spines extend', section='Fins', subsection='Shape', group='Tail Fin', changes='Extends spine at bottom of the tail fin or retracts it towards body', low='Long pointed lower lobe hanging below the fin', high='Lobe fully retracted, compact tail', safe_min=0, safe_max=127, safe_note='0-124', real_range='6-70', crash_risk=False, discrete_values=None),
    dict(offset=0x31E, label='Tail fin middle spines extend', section='Fins', subsection='Shape', group='Tail Fin', changes='Extends spine in middle of the tail fin or retracts it towards body', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x317, label='Tail width/roundness', section='Fins', subsection='Shape', group='Tail Fin', changes='Makes top and bottom of tail fin convex curves or concave cutouts', low=None, high=None, safe_min=0, safe_max=90, safe_note='0-120', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x315, label='Tail rotation', section='Fins', subsection='Shape', group='Tail Fin', changes='Up/down rotation of the middle of the tail fin', low=None, high=None, safe_min=0, safe_max=96, safe_note='0-120', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x314, label='Tail heart shape', section='Fins', subsection='Shape', group='Tail Fin', changes='Rounded convex heart at 0, concave forked tail by 127', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x316, label='Tail vertical bend', section='Fins', subsection='Shape', group='Tail Fin', changes='Tilts end of the tail downward or upward', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x318, label='Tail fin vertical bend', section='Fins', subsection='Shape', group='Tail Fin', changes='Same as 0x316 but tail remains wider', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x280, label='Tail angle', section='Fins', subsection='Shape', group='Tail Fin', changes='Angles the tail down at 0, up at 127', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x31C, label='Tail fin outline shape (single notch)', section='Fins', subsection='Shape', group='Tail Fin', changes='Sibling of 0x314; produces one central concave notch instead of two', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Colour / Dorsal Fin -----------------------------------------
    dict(offset=0x43A, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Dorsal fin colour change, faded at top of fin', low='Colour band A', high='Colour band B', safe_min=0, safe_max=247, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x438, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Colour shading of dorsal fin', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x43D, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Dorsal fin colour change, faded at bottom of fin', low=None, high=None, safe_min=0, safe_max=246, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x43C, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Colour of the middle-to-rear top edge of the dorsal fin specifically, not the whole fin', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x435, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Fade at top of fin', low=None, high=None, safe_min=0, safe_max=1, safe_note='0 = desaturated; 1-255 = normal', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x43B, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Shading at top of fin', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x436, label='Dorsal fin colour', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Shading around front/back of fin', low=None, high=None, safe_min=0, safe_max=1, safe_note='0 = one tone; 1-255 = alternate tone', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x439, label='Dorsal darkness', section='Fins', subsection='Colour', group='Dorsal Fin', changes='Changes dorsal fin to dark', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Colour / Pectoral Fin ---------------------------------------
    dict(offset=0x4F8, label='Pectoral fin brightness', section='Fins', subsection='Colour', group='Pectoral Fin', changes='Darkens front of pectoral fin', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4FB, label='Pectoral fin brightness', section='Fins', subsection='Colour', group='Pectoral Fin', changes='Darkens back of pectoral fin', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4F9, label='Pectoral fin greyscale', section='Fins', subsection='Colour', group='Pectoral Fin', changes='Darkens fin at front, seems to change it to greyscale', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4FC, label='Pectoral fin greyscale', section='Fins', subsection='Colour', group='Pectoral Fin', changes='Darkens fin at back, seems to change it to greyscale', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255 (two-tier)', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Colour / Anal Fin -------------------------------------------
    dict(offset=0x4C8, label='Anal fin brightness', section='Fins', subsection='Colour', group='Anal Fin', changes='Darkens anal fin', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4CB, label='Anal fin darkness', section='Fins', subsection='Colour', group='Anal Fin', changes='Darkens end of fin.', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4EF, label='Anal fin stripe darken', section='Fins', subsection='Colour', group='Anal Fin', changes='Darkens the stripes between spines', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4F1, label='Anal fin rainbow', section='Fins', subsection='Colour', group='Anal Fin', changes='Another confirmed rainbow-family sibling on the same pelvic fin stripe/fill region', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4F2, label='Anal fin darken', section='Fins', subsection='Colour', group='Anal Fin', changes='Darkens end of fin', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255 (discrete)', real_range='real fish only ever use 3 values', crash_risk=False, discrete_values=None),
    dict(offset=0x4C9, label='Anal fin colour flag', section='Fins', subsection='Colour', group='Anal Fin', changes='Two-tier flag rather than a rotation; off at the extremes, low-intensity in the middle, stronger through the upper range', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255 (two-tier)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4CC, label='Anal fin colour', section='Fins', subsection='Colour', group='Anal Fin', changes='Changes colour of fin', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255 (multi-tier)', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Colour / Pelvic Fin -----------------------------------------
    dict(offset=0x52B, label='Pelvic fin colour', section='Fins', subsection='Colour', group='Pelvic Fin', changes='Colours fin from back', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x52C, label='Pelvic fin colour', section='Fins', subsection='Colour', group='Pelvic Fin', changes='Turns greyscale from back', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x528, label='Pelvic fin colour', section='Fins', subsection='Colour', group='Pelvic Fin', changes='Colours fin from the front', low=None, high=None, safe_min=0, safe_max=197, safe_note='0-255 (two-zone)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x529, label='Pelvic fin colour', section='Fins', subsection='Colour', group='Pelvic Fin', changes='Colours fin from front', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255 (staircase)', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Colour / Tail Fin -------------------------------------------
    dict(offset=0x55A, label='Tail fin stripe colours', section='Fins', subsection='Colour', group='Tail Fin', changes='Changes colour of stripes', low=None, high=None, safe_min=0, safe_max=246, safe_note='0-255 (two-state)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x55D, label='Tail fin spine colours', section='Fins', subsection='Colour', group='Tail Fin', changes='Changes colour of stripes', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x582, label='Tail fin darkness', section='Fins', subsection='Colour', group='Tail Fin', changes='Lightens/darkens tail stripes', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x583, label='Tail fin colours', section='Fins', subsection='Colour', group='Tail Fin', changes='Changes colour of stripes', low=None, high=None, safe_min=0, safe_max=243, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x580, label='Tail fin colour stripes', section='Fins', subsection='Colour', group='Tail Fin', changes='Changes colour of stripes', low=None, high=None, safe_min=0, safe_max=246, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x559, label='Tail fin tripes', section='Fins', subsection='Colour', group='Tail Fin', changes='Changes colour of fin', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x555, label='Tail fin contrast', section='Fins', subsection='Colour', group='Tail Fin', changes='Darkens fin', low=None, high=None, safe_min=0, safe_max=1, safe_note='0 = low contrast; 1-255 = high contrast', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x558, label='Tail fin stripe darken', section='Fins', subsection='Colour', group='Tail Fin', changes='Darkens stripes', low=None, high=None, safe_min=0, safe_max=120, safe_note='0-127 = cool tone; 128-255 = warm tone', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x55C, label='Tail fin stripe shading', section='Fins', subsection='Colour', group='Tail Fin', changes='Darkens stripes', low=None, high=None, safe_min=0, safe_max=240, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x57C, label='Tail fin shading flag', section='Fins', subsection='Colour', group='Tail Fin', changes='Alternate shading flag', low=None, high=None, safe_min=0, safe_max=1, safe_note='0 = normal; 1-255 = alternate', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x57A, label='Tail fin shading flag', section='Fins', subsection='Colour', group='Tail Fin', changes='Lightens fin', low=None, high=None, safe_min=0, safe_max=13, safe_note='0 = normal; 1-127 = alternate', real_range='Not established', crash_risk=True, discrete_values=None),
    # -- Pattern / Pectoral Fin --------------------------------------
    dict(offset=0x4FA, label='Pectoral fin colour pattern', section='Fins', subsection='Pattern', group='Pectoral Fin', changes='Changes colour patterns including rainbow', low=None, high=None, safe_min=0, safe_max=233, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Pattern / Anal Fin ------------------------------------------
    dict(offset=0x4CA, label='Anal fin rainbow', section='Fins', subsection='Pattern', group='Anal Fin', changes='Rainbow colours on fin.', low=None, high=None, safe_min=0, safe_max=233, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4F0, label='Pelvic fin rainbow', section='Fins', subsection='Pattern', group='Anal Fin', changes='Rainbow colours on fin.', low=None, high=None, safe_min=0, safe_max=246, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4EE, label='Anal fin stripes', section='Fins', subsection='Pattern', group='Anal Fin', changes='Fades in dark stripes', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4ED, label='Anal fin stripe flag', section='Fins', subsection='Pattern', group='Anal Fin', changes='Turns stripes on or off', low=None, high=None, safe_min=0, safe_max=128, safe_note='0 & 128-255 = olive; 1-127 = blue', real_range='Not established', crash_risk=False, discrete_values=[0, 1, 128]),
    dict(offset=0x4E5, label='Anal fin stripe fade', section='Fins', subsection='Pattern', group='Anal Fin', changes='Fades fin stripes in', low=None, high=None, safe_min=0, safe_max=103, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4E4, label='Anal fin stripe pattern rotate', section='Fins', subsection='Pattern', group='Anal Fin', changes='Rotates the stripes on the anal fin.', low=None, high=None, safe_min=0, safe_max=247, safe_note='0-255', real_range="real fish never vary this) -- note: bbox matches the confirmed pelvic-colour family's region, so this one's placement is the least certain of the six", crash_risk=False, discrete_values=None),
    dict(offset=0x4F3, label='Anal fin stripe colour', section='Fins', subsection='Pattern', group='Anal Fin', changes='Changes colour of stripes', low=None, high=None, safe_min=0, safe_max=246, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4E1, label='Anal fin colour pattern', section='Fins', subsection='Pattern', group='Anal Fin', changes='Changes stripe pattern on anal fin', low=None, high=None, safe_min=0, safe_max=53, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4E2, label='Anal fin spine pattern rotation', section='Fins', subsection='Pattern', group='Anal Fin', changes='Rotates stripes', low=None, high=None, safe_min=0, safe_max=252, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x4E3, label='Anal fin patterns', section='Fins', subsection='Pattern', group='Anal Fin', changes='Changes patterns on fin', low=None, high=None, safe_min=0, safe_max=252, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    # -- Pattern / Tail Fin ------------------------------------------
    dict(offset=0x57D, label='Tail fin stripes flag', section='Fins', subsection='Pattern', group='Tail Fin', changes='Turns on or off stripes', low=None, high=None, safe_min=0, safe_max=128, safe_note='0 = warm; 1-255 = cool', real_range='Not established', crash_risk=False, discrete_values=[0, 1, 128]),
    dict(offset=0x573, label='Tail fin pattern', section='Fins', subsection='Pattern', group='Tail Fin', changes='Changes different patterns on the fin', low=None, high=None, safe_min=0, safe_max=251, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x571, label='Tail fin stripes', section='Fins', subsection='Pattern', group='Tail Fin', changes='Different stripe patterns on tail', low=None, high=None, safe_min=0, safe_max=52, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x572, label='Tail fin pattern selector', section='Fins', subsection='Pattern', group='Tail Fin', changes='Changes patterns on tail fin', low=None, high=None, safe_min=0, safe_max=251, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x575, label='Tail fin vertical stripes', section='Fins', subsection='Pattern', group='Tail Fin', changes='Vertical stripes on tail fin', low=None, high=None, safe_min=0, safe_max=249, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x5A4, label='Tail fin tip stripe', section='Fins', subsection='Pattern', group='Tail Fin', changes='Adds stripe to end of tail', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255 (3-state)', real_range='Not established', crash_risk=False, discrete_values=[0, 1, 100, 128]),
    dict(offset=0x581, label='Tail fin pattern/texture', section='Fins', subsection='Pattern', group='Tail Fin', changes='Changes tail fin stripes', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x57E, label='Tail fin discrete pattern selector', section='Fins', subsection='Pattern', group='Tail Fin', changes='Changes tail fin patterns', low=None, high=None, safe_min=0, safe_max=237, safe_note='0-255 (discrete)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x574, label='Tail fin stripe curve', section='Fins', subsection='Pattern', group='Tail Fin', changes='Curves the stripes', low=None, high=None, safe_min=0, safe_max=247, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x578, label='Tail fin base shading patterns', section='Fins', subsection='Pattern', group='Tail Fin', changes='Changes stripe pattern', low=None, high=None, safe_min=0, safe_max=156, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    # ======================================== Body ========================================
    # -- Body Shape --------------------------------------------------
    dict(offset=0x26C, label='body size', section='Body', subsection=None, group='Body Shape', changes='Scales the body', low='Smaller body, colour A', high='Bigger body, colour B', safe_min=0, safe_max=127, safe_note='0-127', real_range='Not established', crash_risk=True, discrete_values=None),
    dict(offset=0x26E, label='Forehead/back profile flatness', section='Body', subsection=None, group='Body Shape', changes='How steep/flat the forehead is towards the back of the fish', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x270, label='Rear-top body shape', section='Body', subsection=None, group='Body Shape', changes='shape of the rear top of the body towards the tail', low='Body bulges out here', high='Body recedes/shrinks here', safe_min=0, safe_max=100, safe_note='0-255', real_range='0-40', crash_risk=False, discrete_values=None),
    dict(offset=0x26F, label='Top half of body shape', section='Body', subsection=None, group='Body Shape', changes='Shapes top half of entire body, from flat to hugely bulging', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x27D, label='Bottom half of body shape', section='Body', subsection=None, group='Body Shape', changes='Shapes bottom half of entire body, from flat to hugely bulging', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x283, label='Bulge of bottom of body', section='Body', subsection=None, group='Body Shape', changes='Increases flatness/curve of bottom of body', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x284, label='Front underside flatness', section='Body', subsection=None, group='Body Shape', changes='How flat/rounded the underside of the body is from the mouth to the belly', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x285, label='Front underside curve', section='Body', subsection=None, group='Body Shape', changes='How curved in/bulged out the front udnerside is around the chin', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x287, label='Rear underside curve', section='Body', subsection=None, group='Body Shape', changes='How bulging/curved the rear underside is', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x288, label='Rear-underside body depth', section='Body', subsection=None, group='Body Shape', changes='How bulging/curved the rear underside is', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x27F, label='Rear-underside body depth', section='Body', subsection=None, group='Body Shape', changes='How bulging/curved the rear underside is by the tail', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x277, label='Forehead/nose curve', section='Body', subsection=None, group='Body Shape', changes='How curved in/bulged out the forehead is', low='Sharp, pointed, snout-like nose', high='Normal rounded forehead', safe_min=0, safe_max=100, safe_note='0-129', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x27C, label='Chin shape', section='Body', subsection=None, group='Body Shape', changes='Juts out the bottom of the jaw', low='Big, pointed chin jutting forward', high='Flatter, blunter chin', safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x274, label='Forehead size', section='Body', subsection=None, group='Body Shape', changes='Bulges out the forehead', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x282, label='Mouth shape', section='Body', subsection=None, group='Body Shape', changes='Flags a big round mouth', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x29F, label='Mouth size', section='Body', subsection=None, group='Body Shape', changes='Extends the mouth/jaw down along the body', low=None, high=None, safe_min=0, safe_max=99, safe_note='0-99 (plateau to 127)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x27A, label='Top-rear shape', section='Body', subsection=None, group='Body Shape', changes='Bulges out top rear half of body', low='Small/shrunk fin', high='Small/shrunk fin (biggest at baseline, ~77)', safe_min=0, safe_max=100, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x275, label='Forehead shape', section='Body', subsection=None, group='Body Shape', changes='Bulges out forehead', low='Small/no bulge (near baseline)', high='Noticeable forehead bulge', safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x27E, label='Rear body / pelvic fin position', section='Body', subsection=None, group='Body Shape', changes='Bulge/curve of rear underside', low='Normal/standard position', high='Pulled up and in toward the body', safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x286, label='Chin/mouth shape', section='Body', subsection=None, group='Body Shape', changes='Changes mouth shape', low='Colour A', high='Colour B (128-255 = same look as value 0)', safe_min=0, safe_max=75, safe_note='0-127', real_range='0-202', crash_risk=False, discrete_values=None),
    # -- Body Colour -------------------------------------------------
    dict(offset=0x363, label='Whole body colour', section='Body', subsection=None, group='Body Colour', changes='Changes body colour and gradient', low='Near baseline', high='Peaks around value 90, then stays elevated', safe_min=0, safe_max=239, safe_note='0-245', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x361, label='Whole body colour', section='Body', subsection=None, group='Body Colour', changes='Changes body colour and gradient', low='Colour band A', high='Colour band B', safe_min=0, safe_max=237, safe_note='0-236 (60-79 dead zone)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x362, label='Body brightness and greyscale', section='Body', subsection=None, group='Body Colour', changes='Changes body tone and becomes grey at higher values', low='Baseline colour (0-16)', high='Fully grey (around 157), other bands elsewhere', safe_min=17, safe_max=223, safe_note='17-239', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x366, label='Whole body colour', section='Body', subsection=None, group='Body Colour', changes='Changes body colour, darker at the underside', low='Olive/khaki green with orange belly', high='Purple/magenta lower body and belly', safe_min=0, safe_max=97, safe_note='0-100', real_range='0-100 (full natural range, totally safe)', crash_risk=False, discrete_values=None),
    dict(offset=0x364, label='Whole body colour', section='Body', subsection=None, group='Body Colour', changes='Changes whole body colour', low='Cooler/greyer tone', high='More saturated green', safe_min=0, safe_max=237, safe_note='0-99, 120-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x365, label='Whole body colour', section='Body', subsection=None, group='Body Colour', changes='Changes body colour, darker at the underside', low='Baseline (0-16 and 240-255 both = no change)', high='Most dramatic shift around value 140 (near-grey/purple) or 176 (blue-violet)', safe_min=17, safe_max=223, safe_note='17-239', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x35E, label='Tone change flag', section='Body', subsection=None, group='Body Colour', changes='Changes whole body tone', low='Only value 0 is different (a cooler tone)', high='Everything from 1-255 looks the same as baseline', safe_min=0, safe_max=1, safe_note='0 only', real_range='Real fish only ever use 0, 92, or 100 (92 and 100 both look identical to baseline)', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x28D, label='Body brightness', section='Body', subsection=None, group='Body Colour', changes='Changes shadow/brightness of body', low='Darker, more saturated teal-blue', high='Lighter mint-green', safe_min=0, safe_max=100, safe_note='0-127', real_range='0-55', crash_risk=False, discrete_values=None),
    dict(offset=0x38C, label='Rainbow hue rotation', section='Body', subsection=None, group='Body Colour', changes='Cycles colour through the rainbow', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x35F, label='Body tone flag', section='Body', subsection=None, group='Body Colour', changes='Changes whole body tone', low='Only value 0 is the "off" state', high='Everything from 1-255 is "on" (does not reset, unlike most switches)', safe_min=0, safe_max=1, safe_note='0 vs 1-255', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    # -- Body Pattern ------------------------------------------------
    dict(offset=0x37A, label='Horizontal stripe size', section='Body', subsection=None, group='Body Pattern', changes='Changes the height of the stripe pattern', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x37E, label='Vertical stripe/dot pattern', section='Body', subsection=None, group='Body Pattern', changes='Adds dot pattern of varying size. Combined with stripes, can look like vertical stripes', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x383, label='Stripe width & lip colour', section='Body', subsection=None, group='Body Pattern', changes='Changes stripe width, also can add coloured lip', low=None, high=None, safe_min=0, safe_max=127, safe_note='0-127', real_range='Not established', crash_risk=True, discrete_values=None),
    dict(offset=0x385, label='Rainbow flag', section='Body', subsection=None, group='Body Pattern', changes='Changes colour of pattern to rainbow', low=None, high=None, safe_min=0, safe_max=255, safe_note='0 vs 1-255', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x386, label='Body spots', section='Body', subsection=None, group='Body Pattern', changes='Adds spots on body', low='Any value 1-127 = spots ON', high='Same "on" look throughout 1-127 (0 and 128-255 = no spots)', safe_min=0, safe_max=1, safe_note='1-127', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x3BF, label='White body stripe', section='Body', subsection=None, group='Body Pattern', changes='Adds a white vertical clownfish-style stripe to the body', low='Any value 1-127 = stripe ON', high='Same "on" look throughout 1-127 (0 and 128-255 = no stripe)', safe_min=0, safe_max=1, safe_note='1-127', real_range='Not established', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x42D, label='Speckle line', section='Body', subsection=None, group='Body Pattern', changes='Adds a speckled line across the face', low=None, high=None, safe_min=8, safe_max=127, safe_note='0x08-0x7F', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x28B, label='Scale texture', section='Body', subsection=None, group='Body Pattern', changes='Scale texture and eye size. Looks buggy at higher values.', low='No texture, no eye ring', high='Heavy texture, red eye ring, darker colour (body shrinks/distorts only past value ~30)', safe_min=3, safe_max=30, safe_note='0-127 (real-fish range 3-30)', real_range='3-30', crash_risk=False, discrete_values=None),
    dict(offset=0x406, label='Head spots', section='Body', subsection=None, group='Body Pattern', changes='Adds spot pattern to head area', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-100 (only sampled at 5 points)', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x398, label='Side spot', section='Body', subsection=None, group='Body Pattern', changes='Adds a dot to the side of the body', low=None, high=None, safe_min=0, safe_max=255, safe_note='0-100', real_range='Not established', crash_risk=False, discrete_values=[0, 49, 99]),
    # ======================================== Other ========================================
    # -- Eyes --------------------------------------------------------
    dict(offset=0x293, label='Eye size', section='Other', subsection=None, group='Eyes', changes='Increases eye size. Also darkens top front of fish body.', low='Big halo + visible pupil dot', high='Halo grows again on this side too, but milder, no pupil dot (128-255 = same as value 0)', safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A0, label='Eye type', section='Other', subsection=None, group='Eyes', changes='Different eye types. Also changes mouth shade.', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A1, label='Eye size (extreme)', section='Other', subsection=None, group='Eyes', changes='Changes eye size from tiny to massive', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x29E, label='Eye size', section='Other', subsection=None, group='Eyes', changes='Changes eye size and gill shape', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A2, label='Eye position flag', section='Other', subsection=None, group='Eyes', changes='Moves eye towards centre of fish', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x2A3, label='Vertical eye position', section='Other', subsection=None, group='Eyes', changes='Moves eye up and down', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x332, label='Eye colour', section='Other', subsection=None, group='Eyes', changes='Changes eye colour slightly', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 32, 34, 73, 128]),
    dict(offset=0x335, label='Eye colour scalar', section='Other', subsection=None, group='Eyes', changes='Different eye colour types', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x336, label='Eye colour scalar', section='Other', subsection=None, group='Eyes', changes='Changes eye colour slightly', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=[0, 128]),
    dict(offset=0x333, label='Vertical pupil position', section='Other', subsection=None, group='Eyes', changes='Slides pupil up and down, distorting eye with it.', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x334, label='Horizontal pupil position', section='Other', subsection=None, group='Eyes', changes='Slides the red pupil left/right', low=None, high=None, safe_min=0, safe_max=100, safe_note='0-127', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x603, label='Eye darkness', section='Other', subsection=None, group='Eyes', changes='Changes eye white colour', low=None, high=None, safe_min=24, safe_max=237, safe_note='0x18-0xEF', real_range='Real fish never vary this byte (always 0 in nature) — synthetic-only effect', crash_risk=False, discrete_values=None),
    dict(offset=0x604, label='Eye darkness', section='Other', subsection=None, group='Eyes', changes='Chnages white to grey or black', low=None, high=None, safe_min=0, safe_max=128, safe_note='0-255 (OFF band ~0x58-0x7F)', real_range='Real fish never vary this byte', crash_risk=False, discrete_values=None),
    dict(offset=0x299, label='Eye/gill/pectoral changes', section='Other', subsection=None, group='Eyes', changes='Changes eye size, gill shape and pectoral fin position', low='Bigger eye, fin roughly normal size', high='Eye medium, fin extends both up and down (biggest fin span) (baseline ~50 is the "normal" combination)', safe_min=0, safe_max=70, safe_note='0-127', real_range='Fixed at 50 in real fish -- never varies naturally', crash_risk=False, discrete_values=None),
    # -- Gills -------------------------------------------------------
    dict(offset=0x3F2, label='Gill line colour toggle', section='Other', subsection=None, group='Gills', changes='Adds different colour gill line', low='Baseline (olive-green) colour', high='Alternate colour (128-255 = back to baseline)', safe_min=0, safe_max=1, safe_note='0x01-0x7F (ON)', real_range='Real fish only use 0, 8, or 100', crash_risk=False, discrete_values=[0, 1]),
    dict(offset=0x343, label='Gill line curve', section='Other', subsection=None, group='Gills', changes='Changes gill line', low='Gill line runs nearly straight down', high='Gill line unchanged (128-255 resets to the straight look)', safe_min=0, safe_max=100, safe_note='0-255', real_range='0-99', crash_risk=False, discrete_values=None),
    dict(offset=0x341, label='Gill slit — second line', section='Other', subsection=None, group='Gills', changes='Adds second gill slit', low='Second slit line fully visible', high='No second slit line (just the normal single line)', safe_min=0, safe_max=100, safe_note='0-255', real_range='Not established', crash_risk=False, discrete_values=None),
    dict(offset=0x29B, label='Gill line, mouth, fin', section='Other', subsection=None, group='Gills', changes='Changes gill line, mouth and pelvic fin position', low='Smaller ventral fin/shadow, tighter frame', high='Larger ventral fin/shadow, taller frame', safe_min=0, safe_max=128, safe_note='0-45, 128-255 (46-127 no effect)', real_range='Always 50 in real fish', crash_risk=False, discrete_values=None),
    dict(offset=0x29C, label='Gill line', section='Other', subsection=None, group='Gills', changes='Changes gill line', low='Darkens toward grey/black', high='Also darkens toward grey/black -- yellow-green sits at baseline, in the middle', safe_min=0, safe_max=85, safe_note='0-127', real_range='Always 50 in real fish', crash_risk=False, discrete_values=None),
    dict(offset=0x34A, label='Gill line', section='Other', subsection=None, group='Gills', changes='Changes gill line', low='Shifted colour', high='Shifted colour (the other direction)', safe_min=0, safe_max=128, safe_note='0-255', real_range='11-99', crash_risk=False, discrete_values=None),
]

GENES = list(GENES_ALL)  # kept as a separate name for compatibility -- same list, same order

# NOTE: a handful of offsets appear twice in GENES_ALL (see module docstring) -- this dict
# keeps whichever one was defined last for any lookup that only wants "a" gene for an offset
# (e.g. nothing in the GUI currently does this for a duplicated offset; each GeneRow carries
# its own full gene dict already, so this is only for convenience/external use).
GENE_BY_OFFSET = {g["offset"]: g for g in GENES_ALL}

# Tab order -- first-seen order of `section` across GENES_ALL, i.e. the guide's own <h2> order.
SECTIONS = ['Fins', 'Body', 'Other']

